// scripts/convertFontToBase64.ts

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const FONTS_DIR = path.join(__dirname, '../src/lib/fonts');
const OUTPUT_FILE = path.join(__dirname, '../src/lib/fonts.ts');

const fonts = [
  { file: 'BookkMyungjo_Light.ttf', name: 'BookkMyungjo', weight: 'normal' },
  { file: 'BookkMyungjo_Bold.ttf', name: 'BookkMyungjo', weight: 'bold' },
];

const convertFontsToBase64 = () => {
  console.log('🔄 폰트 변환 시작...');
  console.log(`📂 폰트 디렉토리: ${FONTS_DIR}`);

  const fontData: Record<string, string> = {};

  fonts.forEach(({ file, name, weight }) => {
    const fontPath = path.join(FONTS_DIR, file);

    if (!fs.existsSync(fontPath)) {
      console.error(`❌ 폰트 파일을 찾을 수 없습니다: ${fontPath}`);
      process.exit(1);
    }

    console.log(`📝 변환 중: ${file}...`);
    const fontBuffer = fs.readFileSync(fontPath);
    const base64 = fontBuffer.toString('base64');

    fontData[`${name}-${weight}`] = base64;
    console.log(`✅ ${file} 변환 완료 (크기: ${Math.round(base64.length / 1024)}KB)`);
  });

  const output = `// Auto-generated font data
// Do not edit this file manually
// Generated by: pnpm run convert-fonts

export const FONTS = {
  'BookkMyungjo-normal': '${fontData['BookkMyungjo-normal']}',
  'BookkMyungjo-bold': '${fontData['BookkMyungjo-bold']}',
};
`;

  fs.writeFileSync(OUTPUT_FILE, output);
  console.log('\n✅ 폰트 변환 완료!');
  console.log(`📄 출력 파일: ${OUTPUT_FILE}`);
  console.log(`📊 총 파일 크기: ${Math.round(fs.statSync(OUTPUT_FILE).size / 1024)}KB`);
};

convertFontsToBase64();
